# G/SettingsBundle/Resources/config/admin.yml
services:
    sonata.admin.settings:
        class: G\SettingsBundle\Admin\SettingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "settings", label: "settings" }
        arguments:
            - ~
            - G\SettingsBundle\Entity\Setting
            - GSettingsBundle:CRUD
        calls:
            - [ setTranslationDomain, [GSettingsBundle]]